### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by Dzertak** [NuclearSnake/Gasolinni#1]
File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by NuclearSnake** [comment]
Hi!

Yes, it's an intended behavior. Usually the google-services.json file is added to .gitignore when hosting repository on public server, because it contains sensitive information. Author's own quotas may be used which can often lead to unpredictable expenses.

Well, short story long: there are crawlers that hunt for google-services.json and other such files through the Github, and use their quotas. Mainly that's the reason.

Also you will find that MapboxInfo class is missing and the corresponding API token with it.

**Comment by NuclearSnake** [comment]
So, basically, to clone project you need also to register your own project on Firebase, get your own google-services.json and that's it! :)
